language: java
jdk:
  - oraclejdk8
before_install:
  - echo $GPG_SECRET_KEYS | base64 --decode | $GPG_EXECUTABLE --import
  - echo $GPG_OWNERTRUST | base64 --decode | $GPG_EXECUTABLE --import-ownertrust
#install:
##  - mvn --settings .travis/settings.xml install -DskipTests=true -Dmaven.javadoc.skip=true -B -V
#  - mvn --settings .travis/settings.xml install -B -V
script:
# FIXME: add gen doc gen src
  - mvn --settings .travis/settings.xml install -B -V
branches:
  only:
    - /^(?i:feature)/.*$/
    - develop
    - master
deploy:
  -
    provider: script
    script: mvn --settings .travis/settings.xml -DskipTests=true clean deploy -B -U
    on:
#      repo: Intuit/Autumn
      repo: jwtodd/Autumn
      branch: master
      jdk: oraclejdk7
